# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FubPzxfkUt457ro3nc8oYW6Ij3SpPqSz
"""

!nvidia-smi

import os
HOME = os.getcwd()
print(HOME)

!pip list | grep torch

# Commented out IPython magic to ensure Python compatibility.
# %pip install "ultralytics<=8.3.40" supervision roboflow
import ultralytics
ultralytics.checks()

!yolo task=detect mode=predict model=yolo11n.pt conf=0.25 source='GccFGJmxCt4afW5NTTBS' save=True

# Commented out IPython magic to ensure Python compatibility.
!mkdir {HOME}/datasets
# %cd {HOME}/datasets

from google.colab import userdata
from roboflow import Roboflow
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="GccFGJmxCt4afW5NTTBS")
project = rf.workspace("grc-utmmu").project("yolov11-prjjg")
version = project.version(8)
dataset = version.download("yolov11")

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=detect mode=train model=yolo11n.pt data={dataset.location}/data.yaml epochs=10 imgsz=640 plots=True

!ls {HOME}/runs/detect/train/

from IPython.display import Image as IPyImage

IPyImage(filename=f'{HOME}/runs/detect/train/confusion_matrix.png', width=600)

from IPython.display import Image as IPyImage

IPyImage(filename=f'{HOME}/runs/detect/train/results.png', width=600)

from IPython.display import Image as IPyImage

IPyImage(filename=f'{HOME}/runs/detect/train/val_batch0_pred.jpg', width=600)

!yolo task=detect mode=val model={HOME}/runs/detect/train/weights/best.pt data={dataset.location}/data.yaml

!yolo task=detect mode=predict model={HOME}/runs/detect/train/weights/best.pt conf=0.25 source={dataset.location}/test/images save=True

import glob
import os
from IPython.display import Image as IPyImage, display

latest_folder = max(glob.glob(f'{HOME}/runs/detect/predict*/'), key=os.path.getmtime)
for img in glob.glob(f'{latest_folder}/*.jpg')[:3]:
    display(IPyImage(filename=img, width=600))
    print("\n")

project.version(dataset.version).deploy(model_type="yolov11", model_path=f"{HOME}/runs/detect/train/")

!pip install inference

import os, random, cv2
import supervision as sv
import IPython
import inference

# Mock secret key for testing
secret_key = "GccFGJmxCt4afW5NTTBS"  # Replace with actual secret key if available

try:
    model_id = project.id.split("/")[1] + "/" + dataset.version
    model = inference.get_model(model_id, userdata.get(secret_key))  # Assuming userdata.get retrieves the key

    # Location of test set images
    test_set_loc = dataset.location + "/test/images/"
    test_images = os.listdir(test_set_loc)

    # Run inference on 4 random test images, or fewer if fewer images are available
    for img_name in random.sample(test_images, min(4, len(test_images))):
        print(f"Running inference on {img_name}")

        # Load image
        image = cv2.imread(os.path.join(test_set_loc, img_name))

        # Perform inference
        results = model.infer(image, confidence=0.4, overlap=30)[0]
        detections = sv.Detections.from_inference(results)

        # Annotate boxes and labels
        box_annotator = sv.BoxAnnotator()
        label_annotator = sv.LabelAnnotator()
        annotated_image = box_annotator.annotate(scene=image, detections=detections)
        annotated_image = label_annotator.annotate(scene=annotated_image, detections=detections)

        # Display annotated image
        _, ret = cv2.imencode('.jpg', annotated_image)
        i = IPython.display.Image(data=ret)
        IPython.display.display(i)
except Exception as e:
    print(f"Error during inference process: {e}")

from google.colab import files
files.download("runs/detect/train/weights/best.pt")